indent = 4
margin = 92
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = true
short_to_long_function_def = true
always_use_return = true
normalize_line_endings = "unix"
trailing_comma = true
join_lines_based_on_source = true
indent_submodule = false
separate_kwargs_with_semicolon = false
surround_whereop_typeparameters = true
variable_call_indent = []
yas_style_nesting = false
annotate_untyped_fields_with_any = true