coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 13%
        threshold: 5%
    patch:
      default:
        target: 13%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "test/"
  - "docs/"
  - "examples/"
  - "*.md"
  - "*.yml"
  - "*.yaml"
  - "*.toml"
  - "*.jl.cov"
  - "*.info"
