name = "PointController"
uuid = "12345678-1234-5678-9abc-123456789abc"
authors = ["User <user@example.com>"]
version = "0.1.0"
description = "Interactive Julia application for controlling a point using WASD keys with GLMakie visualization"
license = "MIT"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
GLMakie = "0.10"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]