name = "PointController"
uuid = "eae52b99-c8d7-4aa0-bde8-6d33da01be07"
authors = ["User <user@example.com>"]
version = "0.1.0"
description = "Interactive Julia application for controlling a point using WASD keys with GLMakie visualization"
license = "MIT"
repository = "https://github.com/bakulev/JuliaTestRocket"
documentation = "https://bakulev.github.io/JuliaTestRocket/"
categories = ["Graphics", "Visualization", "GUI"]
keywords = ["visualization", "interactive", "graphics", "makie", "gui", "wasd", "keyboard", "control", "real-time", "julia"]

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
GLMakie = "0.10, 0.11, 0.12, 0.13"
Logging = "1"
julia = "1.10"

# CompatHelper configuration
# Automatically update patch versions, require manual approval for minor/major
# Update frequency: weekly for patches, monthly for minor versions

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]