name = "PointController"
uuid = "eae52b99-c8d7-4aa0-bde8-6d33da01be07"
keywords = ["visualization", "interactive", "graphics", "makie", "gui", "wasd", "keyboard", "control", "real-time", "julia"]
license = "MIT"
authors = ["User <user@example.com>"]
categories = ["Graphics", "Visualization", "GUI"]
description = "Interactive Julia application for controlling a point using WASD keys with GLMakie visualization"
documentation = "https://bakulev.github.io/JuliaTestRocket/"
repository = "https://github.com/bakulev/JuliaTestRocket"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Dates = "1"
GLMakie = "0.10, 0.11, 0.13"
Logging = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
