name: Bug Report
description: File a bug report to help us improve JuliaTestRocket
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
  - type: input
    id: julia-version
    attributes:
      label: Julia Version
      description: What version of Julia are you running?
      placeholder: ex. 1.10.0
    validations:
      required: true
      
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: ex. Ubuntu 22.04, macOS 14.0, Windows 11
    validations:
      required: true
      
  - type: input
    id: graphics
    attributes:
      label: Graphics Information
      description: What graphics card and drivers are you using?
      placeholder: ex. NVIDIA RTX 3080, driver version 525.60.11
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide minimal code to reproduce the issue
      render: julia
      placeholder: |
        using GLMakie
        GLMakie.activate!()
        using PointController
        run_point_controller()
        # ... steps that cause the bug
    validations:
      required: true
      
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: If there's an error message, please paste it here
      render: text
      placeholder: Paste the complete error message here
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue
    validations:
      required: false