name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'  # LTS
          - '1.11'  # Latest stable
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@v1

      - name: Install dependencies
        shell: bash
        run: |
          julia --project=. -e "
            using Pkg
            Pkg.instantiate()
          "

      - name: Run tests (Pkg.test with CairoMakie from [targets] test)
        env:
          JULIA_NUM_THREADS: 2
        shell: bash
        run: |
          julia --project=. -e "
            using Pkg
            Pkg.test()
          "
          
  # Optional GLMakie smoke test (only for interactive features)
  smoke-glmakie:
    name: GLMakie Smoke Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          
      - uses: julia-actions/cache@v1
      
      - name: Install X11/Mesa & xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev \
            libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
          
      - name: Install dependencies
        run: |
          julia --project=. -e "
            using Pkg
            Pkg.instantiate()
            Pkg.add(\"GLMakie\")
          "
          
      - name: Run GL smoke test under xvfb
        run: |
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' \
            julia --project=. -e "
              using GLMakie
              GLMakie.activate!()
              using Pkg
              # Only run the GLMakie smoke test, not all tests
              include(\"test/test_glmakie_smoke.jl\")
            "
          
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Run Aqua quality checks (CI mode)
        run: julia --project=test scripts/quality_ci.jl