name: Format Check
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Check formatting (temp env)
        run: julia scripts/format_ci.jl